### ISSUE TITLE
WebStorm code format for Dust template

### ISSUE THREAD

**Issue by sumpton** [yifanz/Intellij-Dust#25]
How do I enable or develop code formatting for WebStorm Dust templates?

**Comment by yifanz** [comment]
Make sure you have the dust template file extension registered:
https://www.jetbrains.com/idea/help/register-new-file-type-association-dialog.html

Code formatting should work the same way as intellij:
https://www.jetbrains.com/idea/help/reformatting-source-code.html

**Comment by sumpton** [comment]
Thank you for your response. I have hesitated writing back because you make it sound so simple. I am obviously doing something wrong.

I had already explored extensively before asking for help, including being sure the file type was associated. To bring it down to my level

Editor > File Types -- where Dust was already associated with *.dust file types (and *.tl) -- which I am using.

I have used the reformat feature about a thousand times on .js scripts -- which works brilliantly.

I don't know if it means anything, but Dust is not listed under

Editor > Code Style

and EJS -- we just switched from EJS -- and other template libraries are listed there.

Is there anything specific I could check or test?

**Comment by yifanz** [comment]
That's okay, I understand what you are asking now – you want to configure the formatting style (tab size, indent, etc) for dust templates.

I didn't write a custom "Code Style" panel for this plugin. Therefore, the dust formatting style will follow the general configuration under "Editor > Code Style" and also be influenced by "Editor > Code Style > HTML" since you will most likely be using HTML tags in your templates.

**Comment by sumpton** [comment]
Now I understand. Thank you.

Part of the problem is that in some templates the formatting was confused by a mix of stuff, including AngularJS and did not seem to handle that very well. I have changed to using Adaro and a base template which makes having balanced tags in partials much easier.

**Comment by sumpton** [comment]
Hi again, and thank you for writing this module. I have been working around the formatting and indentation for our dust templates, but perhaps I am missing something obvious. The problem is if I reformat a dust template the indentations get confused and large blocks line up on the left edge. These templates also have Angular markup.

If I temporarily replace the {} brackets that script formats great. I have been using <%% and  %%>  to replace the open and closing brackets, reformat and switch them back, but other developers must have this working.
